_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  AQE: 
    ENABLED: False
  RERANK:
    ENABLED: False

OUTPUT_DIR: logs/market1501/sbs_R101-ibn
