_BASE_: ../Base-HTLee.yml

MODEL:
  META_ARCHITECTURE: "MoReID"

  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True

SOLVER:
  BASE_LR: 0.003

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  AQE: 
    ENABLED: False
  RERANK:
    ENABLED: True

OUTPUT_DIR: logs/market1501/sbs_R101-ibn
